#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

if [ -d "${OPENSHIFT_DATA_DIR}/uploads" ]; then
  echo "5. ------ Restoring stored pictures ------"
  cp -r "${OPENSHIFT_DATA_DIR}/uploads" "${OPENSHIFT_REPO_DIR}/public"
fi

